const Sequelize = require('sequelize')

const sequelize = require('../util/DBconnection')

const EmpreendimentoUnidade = sequelize.define('empreendimentos_unidades', {
  id_unidade: {
    type: Sequelize.INTEGER,
    autoIncrement: true,
    allowNull: false,
    primaryKey: true
  },
  tipo: Sequelize.INTEGER,
  status: Sequelize.INTEGER,
  numero: Sequelize.STRING(12),
  area_real: Sequelize.DECIMAL(10, 4),
  area_privativa: Sequelize.DECIMAL(10, 4),
  fator: Sequelize.DECIMAL(12, 8),
  valor_tabela: Sequelize.DECIMAL(14, 4),
  margem_negocial: Sequelize.DECIMAL(10, 2),
  tipologia: Sequelize.STRING(10),
  caracteristicas: Sequelize.STRING(40),
  localizacao: Sequelize.STRING(10),
  pagina: Sequelize.INTEGER,
  linha: Sequelize.INTEGER,
  id_bloco: Sequelize.INTEGER,
  id_empreendimento: Sequelize.INTEGER,
  garagem_dupla: Sequelize.INTEGER,
  peso01: Sequelize.DECIMAL(10, 4),
  peso02: Sequelize.DECIMAL(10, 4),
  peso03: Sequelize.DECIMAL(10, 4),
  peso04: Sequelize.DECIMAL(10, 4),
  peso05: Sequelize.DECIMAL(10, 4),
  peso06: Sequelize.DECIMAL(10, 4),
  agrupamento: Sequelize.INTEGER,
  und_preco_m2: Sequelize.INTEGER,
  preco_independente: Sequelize.INTEGER,
  preco_m2_01: Sequelize.DECIMAL(10, 4),
  preco_m2_01_old: Sequelize.DECIMAL(10, 4),
  preco_m2_02: Sequelize.DECIMAL(10, 4),
  preco_m2_02_old: Sequelize.DECIMAL(10, 4),
  area_comum_proporc: Sequelize.DECIMAL(10, 4),
  area_comum_nao_proporc: Sequelize.DECIMAL(10, 4),
  area_construcao: Sequelize.DECIMAL(10, 4),
  fracao_terreno: Sequelize.DECIMAL(10, 6),
  localizacao2: Sequelize.STRING(40),
  id_proposta: Sequelize.INTEGER,
  taxa_vpl_negativo: Sequelize.DECIMAL(10, 4),
  ctb_enviado: Sequelize.INTEGER,
  id_locacao: Sequelize.INTEGER,
  ck_locacao: Sequelize.INTEGER,
  ck_locado: Sequelize.INTEGER,
  valor_contabil: Sequelize.DECIMAL(13, 2),
  conta_debito: Sequelize.INTEGER,
  status_ctb: Sequelize.INTEGER,
  valor_fundo_promocao: Sequelize.DECIMAL(10, 2),
  valor_locacao_cota: Sequelize.DECIMAL(12, 2),
  valor_condominio: Sequelize.DECIMAL(10, 2),
  valor_iptu: Sequelize.DECIMAL(10, 2),
  descricao_tabela_locacao: Sequelize.STRING(70),
  ck_locacaovenda: Sequelize.INTEGER,
  ck_segunda_unidade: Sequelize.INTEGER,
  id_unidade_portal: Sequelize.INTEGER,
  id_po_unidades_nome_unidade: Sequelize.INTEGER,
  ck_locacaocliente: Sequelize.INTEGER,
  ck_locacaovos: Sequelize.INTEGER,
  id_empresa: Sequelize.INTEGER,
}, {
  timestamp: false,
  createdAt: false,
  updatedAt: false
});

module.exports = EmpreendimentoUnidade
